"""
Created on Sat Dec 12 17:00:00 2023

@author: Anna Grim
@email: anna.grim@alleninstitute.org

...

"""

import networkx as nx
import os
from concurrent.futures import ProcessPoolExecutor, as_completed
from random import sample

import numpy as np

from deep_neurographs import graph_utils as gutils
from deep_neurographs import swc_utils, utils

BATCH_PERCENT = 0.25


def get_accepted_propoals_blocks(
    neurographs,
    preds,
    blocks,
    block_to_idxs,
    idx_to_edge,
    high_threshold=0.9,
    low_threshold=0.6,
    structure_aware=True,
):
    accepts = dict()
    for block_id in blocks:
        # Get accepts
        preds = threshold_preds(
            preds,
            idx_to_edge,
            low_threshold,
            valid_idxs=block_to_idxs[block_id],
        )

        # Refine accepts wrt structure
        if structure_aware:
            graph = neurographs[block_id].copy()
            accepts[block_id] = get_structure_aware_accepts(
                neurographs[block_id],
                graph,
                preds,
                high_threshold=high_threshold,
                low_threshold=low_threshold,
            )
        else:
            accepts[block_id] = preds.keys()
    return accepts


def get_accepted_proposals(
    neurograph,
    graph,
    preds,
    idx_to_edge,
    high_threshold=0.9,
    low_threshold=0.6,
    structure_aware=True,
):  
    # Get positive edge predictions
    preds = threshold_preds(preds, idx_to_edge, low_threshold)
    if structure_aware:
        return get_structure_aware_accepts(
            neurograph,
            graph,
            preds,
            high_threshold=high_threshold,
            low_threshold=low_threshold,
        )
    else:
        return preds.keys()


def threshold_preds(preds, idx_to_edge, threshold, valid_idxs=[]):
    """
    Thresholds predictions by iterating over "preds" and checking whether a
    given predicted probability is above "threshold".

    Parameters
    ----------
    preds : list
        Predicted probabilities generated by a machine learning model.
    idx_to_edge : dict
        Maps indices correspond to "preds" to an edge proposal id.
    threshold : float
        Number between 0 and 1 to threshold predicted probabilites.
    valid_idxs : list, optional
        List of indices that are valid to accept, applicable in the case where
        inference is being run on multiple blocks. The default is [].

    Returns
    -------
    thresholded_preds
        Dictionary generated from "preds" whose probability is above
        threshold, where each item is an edge proposal id and corresponding
        predicted probability.

    """
    print(preds)
    thresholded_preds = dict()
    for i, pred_i in enumerate(preds):
        contained_bool = True if len(valid_idxs) == 0 else i in valid_idxs
        if pred_i > threshold and contained_bool:
            thresholded_preds[idx_to_edge[i]] = pred_i
    return thresholded_preds


def get_structure_aware_accepts(
    neurograph, graph, preds, high_threshold=0.8, low_threshold=0.6
):
    # Add best preds
    best_preds, best_probs = get_best_preds(neurograph, preds, high_threshold)
    accepts = check_cycles_sequential(graph, best_preds, best_probs)
    if len(best_preds) == len(preds.keys()):
        return accepts

    # Add remaining preds
    best_preds = set(best_preds)
    good_preds = []
    good_probs = []
    for edge, prob in preds.items():
        if edge not in best_preds:
            good_preds.append(edge)
            good_probs.append(prob)

    more_accepts = check_cycles_sequential(graph, good_preds, good_probs)
    accepts.extend(more_accepts)    
    return accepts


def get_subgraphs(graph, edge):
    """
    Gets the connected component subgraphs corresponding to the nodes in edge.

    Parameters
    ----------
    graph : networkx.Graph
        Graph to be searched
    edge : frozenset
        Edge that connected components are extracted with.

    Returns
    -------
    networkx.Graph
        Connected component subgraphs corresponding to the nodes in edge.

    """
    i, j = tuple(edge)
    subgraph_1 = graph.subgraph(gutils.get_component(graph, i))
    subgraph_2 = graph.subgraph(gutils.get_component(graph, j))
    return nx.union(subgraph_1, subgraph_2)


def check_cycles_parallelized(graph, edge_list):
    """
    Checks whether each edge in "edge_list" creates a cycle in "graph" in a
    with a parallelized algorithm.

    Parameters
    ----------
    graph : networkx.Graph
        Graph to be searched.
    edge_list : list
        List of edges to be checked.

    Returns
    -------
    graph : networkx.Graph
        Graph with each edge in "edge_list" added
    fail : bool
        Indication of whether a cycle was created due to parallelization.

    """
    # Assign processes
    with ProcessPoolExecutor() as executor:
        processes = []
        for edge in edge_list:
            subgraph = get_subgraphs(graph, edge)
            executor.submit(gutils.creates_cycle, subgraph, edge)

    # Store result
    accepts = []
    for process in as_completed(processes):
        created_cycle, edge = process.result()
        if not created_cycle:
            accepts.append(edge)
            graph.add_edge_from([edge])

    fail = True if gutils.cycle_exists(graph) else False
    return accepts, fail


def check_cycles_sequential(graph, edges, probs):
    accepts = []
    for i in np.argsort(probs):
        subgraph = get_subgraphs(graph, edges[i])
        created_cycle, _ = gutils.creates_cycle(subgraph, tuple(edges[i]))
        if not created_cycle:
            graph.add_edges_from([tuple(edges[i])])
            accepts.append(edges[i])
    return accepts


def get_best_preds(neurograph, preds, threshold):
    edges = []
    probs = []
    for edge, prob in preds.items():
        if neurograph.is_simple(edge) and prob > threshold:
            edges.append(edge)
            probs.append(prob)
    return edges, probs


def fuse_branches(neurograph, edges):
    for edge in edges:
        if neurograph.is_simple(edge):
            neurograph.merge_proposal(edge)
        else:
            print("merge not implemented for complex")
    return neurograph


# -- Save result --
def save_prediction(neurograph, proposal_preds, output_dir):
    # Initializations
    corrections_dir = os.path.join(output_dir, "corrections")
    utils.mkdir(output_dir, delete=True)
    utils.mkdir(corrections_dir, delete=True)

    # Write Result
    neurograph.to_swc(output_dir)
    save_corrections(neurograph, proposal_preds, corrections_dir)


def save_corrections(neurograph, proposal_preds, output_dir):
    for cnt, (i, j) in enumerate(proposal_preds):
        # Info
        color = f"1.0 1.0 1.0"
        filename = f"merge-{cnt + 1}.swc"
        path = os.path.join(output_dir, filename)

        # Save
        xyz_i = neurograph.nodes[i]["xyz"]
        xyz_j = neurograph.nodes[j]["xyz"]
        swc_utils.save_edge(path, xyz_i, xyz_j, color=color, radius=3)
